spring.application.name=Assignment9-28-Feb-Library-Management-System

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/SpringBoot
spring.datasource.username=postgres
spring.datasource.password=2580
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
