FROM eclipse-temurin:17.0.18_8-jdk


LABEL "org.opencontainer.author"="dockerprac"

COPY /target/Docker_prac-0.0.1-SNAPSHOT.jar Docker_prac-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","Docker_prac-0.0.1-SNAPSHOT.jar"]